export const UI_CONSTANTS = {
  FONT_FAMILY: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Helvetica,Arial,sans-serif',

  LOGO_PROPORTION: '0.2849',

  GLOBAL_LINE_HEIGHT: '1.5',

  GRID_GAP_SIZE: '20px',

  ELEVATION_SHADOW_1: '0 1px 3px 0 rgba(0, 0, 0, 0.1)',
  ELEVATION_SHADOW_2: '0 3px 10px rgba(0, 0, 0, 0.05)',
  ELEVATION_SHADOW_3: '0 5px 15px rgba(0, 0, 0, 0.05)',

  FONT_SIZE_HERO_LARGE: '46px',

  FONT_SIZE_LARGE: '18px',
  FONT_SIZE_MEDIUM: '16px',
  FONT_SIZE_BASE: '14px',
  FONT_SIZE_SMALL: '12px',
  FONT_SIZE_TINY: '10px',

  HEADER_HEIGHT: '60px',
  FOOTER_HEIGHT: '60px',

  ASIDE_WIDTH: '230px',

  PADDING_HORIZONTAL_GLOBAL: '25px',
  PADDING_VERTICAL_GLOBAL: '20px',
  PADDING_HORIZONTAL_ELEMENT: '20px',
  PADDING_VERTICAL_ELEMENT: '10px',

  INPUT_SIDE_PADDING: '12px',
  INPUT_HEIGHT_SMALL: '36px',
  INPUT_HEIGHT_LARGE: '44px',

  BORDER_RADIUS_SMALL: '4px',
  BORDER_RADIUS_MEDIUM: '8px',
  BORDER_RADIUS_LARGE: '12px',

  SQUARED_ICON_SIZE: '24px',
};
